# Generated by Django 4.0.5 on 2023-01-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HourSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting HourSlot.', verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=50, unique=True)),
                ('code', models.IntegerField(default=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting WeekDay.', verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DoctorDay_day', to='task.weekday')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DoctorDay_doctor', to='task.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'day')},
            },
        ),
        migrations.CreateModel(
            name='DoctorDaySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorDaySlot_day', to='task.doctorday')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorDay_slot', to='task.hourslot')),
            ],
            options={
                'unique_together': {('doctor_day', 'slot')},
            },
        ),
    ]
